# Generated by Django 5.2.6 on 2025-10-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Rewiew',
                'verbose_name_plural': 'Rewiews',
            },
        ),
    ]
