# Generated by Django 5.2.6 on 2025-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
