# Generated by Django 5.2.6 on 2025-10-20 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rewiew_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewiew',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
