# Generated by Django 5.2.6 on 2025-10-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItmem',
            new_name='CartItem',
        ),
    ]
